[package]
name = "shining-piano-web"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
shining-piano-core = { path = "../core" }
bevy = { workspace = true }
bevy-midi-graph = { workspace = true }
wasm-bindgen = "0.2"

